export 'contador_clicks.dart';
export 'fotos_columna.dart';
export 'fotos_pantalla.dart';
export 'fotos_piramides.dart';
export 'iconos_pantalla.dart';
export 'juego_imagenes.dart';
export 'nombre_pantalla.dart';
export 'instagram/main_instagram.dart';
export 'menu_lateral.dart';